<Workspace Version="0.8.3.2391" X="253.152416173717" Y="-142.535580977078" zoom="2.12842063749437" Name="patternFromSolidModule" Description="Creates a pattern by arraying and rotating a solid module" ID="967d774a-9958-4e57-bbb8-c46d1924d7af" Category="Geometry.Solid">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cylinder" resolvedName="Autodesk.DesignScript.Geometry.Cylinder" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSIronPythonNode.PythonNode guid="bf17d902-d1be-4f99-bc77-8d2ca3ba1079" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="189.043467200351" y="123.630151030275" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="4">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variables.
solid = IN[0]
val = IN[1]
xCount = IN[2]
yCount = IN[3]

#create an empty list for the arrayed solids
solids = []
#create an empty list for the edge curves
crvs = []
#create number ranges for X and Y
xRange = list(range(xCount))
yRange = list(range(yCount))

#Get edges and convert to curve geometry - we need these curves due to a bounding box bug
edges = solid.Edges
for edge in edges:
	crvs.append(edge.CurveGeometry)
	
#Get the bounding box of the curves
bbox = BoundingBox.ByGeometry(crvs)

#Get the X and Y translation distance based on the bounding box
yDist = bbox.MaxPoint.Y-bbox.MinPoint.Y
xDist = bbox.MaxPoint.X-bbox.MinPoint.X

#Loop through X and Y
for i in xRange:
	for j in yRange:
		#get the source coordinate system
		fromCoord = solid.ContextCoordinateSystem
		#Rotate and translate the coordinate system
		toCoord = fromCoord.Rotate(solid.ContextCoordinateSystem.Origin,Vector.ByCoordinates(0,0,1),(90*(i+j%val)))
		vec = Vector.ByCoordinates((xDist*i),(yDist*j),0)
		toCoord = toCoord.Translate(vec)
		#Transform the solid from the source coordinate system to the target coordinate system and append to the list
		solids.append(solid.Transform(fromCoord,toCoord))


#Assign your output to the OUT variable.
OUT = solids</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol guid="0de6a940-9292-491b-a0f4-7ff512ddefcd" type="Dynamo.Nodes.Symbol" nickname="Input" x="-28.9275126138078" y="88.7794351420717" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="solid:Solid" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="fba0b290-6222-41a1-ad7e-90ae4ef144d6" type="Dynamo.Nodes.Symbol" nickname="Input" x="-30.4451097957236" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="seed:int = 3" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="894e8d8d-cbc7-425b-ae42-379701e9d5e7" type="Dynamo.Nodes.Symbol" nickname="Input" x="-30.4451097957236" y="211.220564857928" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="xCount:int = 10" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="15f1b2fc-6aed-464a-8cef-6c1e9364d44b" type="Dynamo.Nodes.Symbol" nickname="Input" x="-30.4451097957236" y="271.682331124899" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="yCount:int = 10" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="bca76fe1-a69e-423a-88bc-7e28bc502327" type="Dynamo.Nodes.Output" nickname="Output" x="388.843467200351" y="123.630151030275" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="solids" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="bf17d902-d1be-4f99-bc77-8d2ca3ba1079" start_index="0" end="bca76fe1-a69e-423a-88bc-7e28bc502327" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0de6a940-9292-491b-a0f4-7ff512ddefcd" start_index="0" end="bf17d902-d1be-4f99-bc77-8d2ca3ba1079" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fba0b290-6222-41a1-ad7e-90ae4ef144d6" start_index="0" end="bf17d902-d1be-4f99-bc77-8d2ca3ba1079" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="894e8d8d-cbc7-425b-ae42-379701e9d5e7" start_index="0" end="bf17d902-d1be-4f99-bc77-8d2ca3ba1079" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="15f1b2fc-6aed-464a-8cef-6c1e9364d44b" start_index="0" end="bf17d902-d1be-4f99-bc77-8d2ca3ba1079" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="2057.98366385335" eyeY="1191.13345732301" eyeZ="-876.282631778849" lookX="-837.115156074734" lookY="-1187.05015198435" lookZ="872.935613180809" upX="-0.110660669552309" upY="0.987136286649364" upZ="0.115395879591157" />
  </Cameras>
</Workspace>