<Workspace Version="0.8.1.1942" X="-3812.70805469766" Y="-3973.74976212649" zoom="1.15647739846617" Name="Home" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cylinder" resolvedName="Autodesk.DesignScript.Geometry.Cylinder" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSCoreNodesUI.Input.IntegerSlider guid="15bd80ce-ad82-4e84-b4b6-09016b00b7fa" type="DSCoreNodesUI.Input.IntegerSlider" nickname="Integer Slider" x="2987.62706610573" y="3785.65872399559" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Int32>5</System.Int32>
      <Range min="-50" max="50" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <DSCoreNodesUI.Input.IntegerSlider guid="abd1a7a9-5b78-4d80-bff0-9203642ffbf2" type="DSCoreNodesUI.Input.IntegerSlider" nickname="Integer Slider" x="2988.13280681572" y="3857.18715129475" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Int32>3</System.Int32>
      <Range min="-50" max="50" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <Dynamo.Nodes.CodeBlockNodeModel guid="18642bf0-d88e-4603-9c05-4eedbc65ec06" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="3324.13530519375" y="3788.34675976877" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="-50..50..#Nx;&#xA;-50..50..#Ny;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="c3d30427-9b4d-4931-8971-52c2bad91ee8" type="Dynamo.Nodes.DSFunction" nickname="Point.ByCoordinates" x="3543.13912255062" y="3784.42503769165" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.Watch guid="1ec3edac-fc95-4f6d-ad4b-1b06e58b8f3b" type="Dynamo.Nodes.Watch" nickname="Watch" x="3736.83075915077" y="3785.2897324979" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSFunction guid="99ecc8d6-ebc0-4ae3-a2bc-1e534882e1bd" type="Dynamo.Nodes.DSFunction" nickname="PolyCurve.ByPoints" x="4385.35186383878" y="3720.4376220291" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="16bd3b8d-0a74-4aae-ad08-330ecd833686" type="Dynamo.Nodes.DSFunction" nickname="List.Transpose" x="4107.78483103231" y="3953.04052491053" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="3ec42ebf-2086-4d05-8cb0-e211a56556b6" type="Dynamo.Nodes.DSFunction" nickname="PolyCurve.ByPoints" x="4396.34430852308" y="3951.06254750107" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="15bd80ce-ad82-4e84-b4b6-09016b00b7fa" start_index="0" end="18642bf0-d88e-4603-9c05-4eedbc65ec06" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="abd1a7a9-5b78-4d80-bff0-9203642ffbf2" start_index="0" end="18642bf0-d88e-4603-9c05-4eedbc65ec06" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="18642bf0-d88e-4603-9c05-4eedbc65ec06" start_index="0" end="c3d30427-9b4d-4931-8971-52c2bad91ee8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="18642bf0-d88e-4603-9c05-4eedbc65ec06" start_index="1" end="c3d30427-9b4d-4931-8971-52c2bad91ee8" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c3d30427-9b4d-4931-8971-52c2bad91ee8" start_index="0" end="1ec3edac-fc95-4f6d-ad4b-1b06e58b8f3b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1ec3edac-fc95-4f6d-ad4b-1b06e58b8f3b" start_index="0" end="99ecc8d6-ebc0-4ae3-a2bc-1e534882e1bd" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1ec3edac-fc95-4f6d-ad4b-1b06e58b8f3b" start_index="0" end="16bd3b8d-0a74-4aae-ad08-330ecd833686" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="16bd3b8d-0a74-4aae-ad08-330ecd833686" start_index="0" end="3ec42ebf-2086-4d05-8cb0-e211a56556b6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>